---
driver:
  name: vagrant

platforms:
  - name: chef/ubuntu-14.04

provisioner:
  name: chef_zero


suites:
  - name: aem
    run_list:
      - recipe[aem-dep::default]
    driver:
      vm_hostname: aem
      customize:
        memory: 4096
        cpus: 2
      network:
        - ["forwarded_port", {guest: 4502, host: 4502}]
        - ["private_network", {ip: "192.168.34.33"}]
      synced_folders:
        - ["data/aem/author", "/adobe/aem/author", "create: true, owner: 'root', group: 'root'"]
  - name: aem2
    run_list:
      - recipe[aem-dep::default]
    driver:
      vm_hostname: aem2
      customize:
        memory: 4096
        cpus: 2
      network:
        - ["forwarded_port", {guest: 4502, host: 4503}]
        - ["private_network", {ip: "192.168.34.34"}]
      synced_folders:
        - ["data/aem/author", "/adobe/aem/author", "create: true, owner: 'root', group: 'root'"]
  - name: aem3
    run_list:
      - recipe[aem-dep::default]
    driver:
      vm_hostname: aem3
      customize:
        memory: 4096
        cpus: 2
      network:
        - ["forwarded_port", {guest: 4502, host: 4504}]
        - ["private_network", {ip: "192.168.34.35"}]
      synced_folders:
        - ["data/aem/author", "/adobe/aem/author", "create: true, owner: 'root', group: 'root'"]
